In [2]:
import pandas as pd 
import numpy as np

In [3]:
import matplotlib.pyplot as plt
import os
import scipy.stats as sts
%matplotlib inline

In [14]:
pd.set_option("display.max_rows", 2000)
pd.set_option("display.max_columns", 999)

In [4]:
ls

 Volume in drive C has no label.
 Volume Serial Number is F236-CBC5

 Directory of C:\Users\Khanh Pham\Documents\pythonfordataanalysis

10/01/2019  08:23 AM    <DIR>          .
10/01/2019  08:23 AM    <DIR>          ..
10/01/2019  08:21 AM    <DIR>          .ipynb_checkpoints
09/04/2019  01:23 PM             3,918 53.txt
09/22/2019  01:02 AM         1,815,718 Biglist 10.01.2018.xlsx
10/01/2019  08:21 AM                72 Biglist.ipynb
09/13/2019  12:23 PM             1,419 Class and Objects.ipynb
09/04/2019  01:02 PM           343,222 Data Exploration.html
09/04/2019  01:02 PM            66,124 Data Exploration.ipynb
09/26/2019  03:29 PM           178,452 Grad OT Contract green.docx
09/13/2019  12:31 PM               555 inhertiance.ipynb
09/04/2019  01:02 PM                23 README.md
09/04/2019  01:02 PM             4,423 sample_submission_predictdata.csv
09/04/2019  01:02 PM            21,955 test_predictdata.csv
09/04/2019  01:02 PM            38,011 train_predictdata.csv
09/04/2019  01:02 PM            61,497 Transactional data.xlsx
09/04/2019  01:02 PM           299,516 Transactional.html
09/04/2019  01:02 PM            29,683 Transactional.ipynb
09/24/2019  10:45 PM           359,185 Untitled.ipynb
10/01/2019  08:23 AM            16,412 WordCloud.ipynb
              17 File(s)      3,240,185 bytes
               3 Dir(s)  56,554,078,208 bytes free

In [5]:
df = pd.read_excel('Biglist 10.01.2018.xlsx',sheet_name="IN-PA")

In [15]:
df.head(10)

,Curr Term,Banner ID,Last Name,First Name,Middle Name,Name Suffix,Preferred First Name,Enrolled/Admitted Status,Gender,Birth Date,Marital Status,Citizenship Type,Nation of Citizenship,Nation of Birth,Visa Type,SEVIS Number,Reported Race,Residency,Student Status,Curr Program,Curr College,Curr Degree,Curr Major 1,Curr Major 2,Curr Level,Curr Class,Class Attr,Curr SGASTDN Student Type,Curr SGASTDN Student Type Desc,Derived Student Type,Derived Student Type Desc,Time Status,Curr AHrs,Overall GPA,Overall EHrs,Campus(es),Primary Advisor,Primary Advisor Email Address,Secondary Advisor(s),Enrollment Date,Catalog Term,Last Enrolled Term,Grad App Term,OKey Username,Student Inst Email Address,Student Alt Email Address,Local Street 1,Local Street 2,Local City,Local State,Local Zip,Local Country,Perm Street 1,Perm Street 2,Perm City,Perm State,Perm Zip,Perm Country,First Admit Term,Admit Term,Application Date,Admit Decision Date,Admit Decision,Admit College,Admit Degree,Admit Major,Admit Student Population,Admit Student Population Desc,All Prior Colleges,All Prior College Names
0,201860,A10005577,Seol,Jong-Ho,NaN,NaN,Jongho,Enrolled,M,1972-04-06,M,IN,KS,KS,F1,N0024902275,Nonresident Alien,I,AS,PHD-CS,AS,PHD,CS,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,9,3.722222,63.0,Stillwater,"Park, Nohpill",n.park@okstate.edu,"Thomas, Johnson P.",NaT,201760,201840.0,NaN,jongho,jongho@okstate.edu,jongho.seol@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,320 E McElroy Rd Apt 305,NaN,Stillwater,OK,74075-3849,NaN,200320,201760.0,2017-04-11,2017-04-13,Admitted,AS,PHD,CS,N,New First Time,FC1384,Samchok Natl Univ
1,201860,A10010945,Yerramsetti,Praveen,Nagh,NaN,Praveen,Enrolled,M,1976-12-20,M,PA,IN,IN,X,N0011558561,Asian,I,AS,PHD-FDSC,AG,PHD,FDSC,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,2,3.763158,110.0,Stillwater,"Bowser, Timothy J.",bowser@okstate.edu,NaN,NaT,201360,201840.0,NaN,yerrams,yerrams@okstate.edu,praveennagh@hotmail.com,"73 South, University Place",Apt # 5,Stilwater,OK,74075,NaN,4519 Aggie Dr Apt 5,NaN,Stillwater,OK,74074-5862,NaN,200220,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,FC0087; FC1235; FC0540; FC2126,Andhra University; Osmania Univ; Gitam Univers...
2,201860,A10042328,Loh,Weng,Kheong,NaN,Ben,Enrolled,M,1982-04-27,S,IN,MY,MY,H1,N0000756882,Nonresident Alien,I,AS,PHD-MAE,EN,PHD,MAE,NaN,GR,GD,GD,C,Continuing,C,Continuing,LH,1,3.650000,138.0,Stillwater,"Jacob, Jamey D.",jdjacob@okstate.edu,"Fore, Charlotte R.; Powers, Beth S.",NaT,200960,201820.0,NaN,wloh,ben.loh@okstate.edu,benloh82@gmail.com,106 E.Eskridge,NaN,Stillwater,OK,74075,NaN,106 E Eskridge Ave,NaN,Stillwater,OK,74075-3801,NaN,200660,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201860,A10042670,Etlapur,Smitha,NaN,NaN,Smitha,Enrolled,F,1983-03-18,NaN,IN,IN,IN,F1,N0001746589,Nonresident Alien,I,AS,GCRT-BDM,GR,GCRT,BDM,NaN,GR,GC,GC,C,Continuing,C,Continuing,LH,3,3.388889,54.0,Stillwater,"Chakraborty, Goutam",goutam.chakraborty@okstate.edu,NaN,NaT,201660,201820.0,NaN,etlapur,smitha.etlapur@okstate.edu,etlapur@gmail.com,1106 W Tyler Ave,NaN,Stillwater,OK,74075,NaN,12704 S 2nd St,NaN,Jenks,OK,74037-2840,NaN,200460,201660.0,2016-06-21,2016-08-01,Admitted,GR,GCRT,BDM,N,New First Time,6546; FC1235,Oklahoma State Univ Stillwater; Osmania Univ
4,201860,A10042761,Jayaseelan,Hema,NaN,NaN,Hema,Enrolled,F,1979-03-18,M,IN,UK,IN,F1,N0012119825,Nonresident Alien,I,AS,PHD-CIVE,EN,PHD,CIVE,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,2,3.918919,98.0,Stillwater,"Russell, Bruce W.",bruce.russell@okstate.edu,"Veenstra, John N.",NaT,201460,201840.0,NaN,hema,hema.jayaseelan@okstate.edu,hemajayaseelan@gmail.com,2119 N Manning Street,NaN,Stillwater,OK,74075,NaN,618 N Manning St,NaN,Stillwater,OK,74075-7800,NaN,200460,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,FC0200,Bharathiar Univ
5,201860,A10482212,Abbasi,Muhammad,Salman,NaN,Salman,Enrolled,M,1980-09-09,S,IN,PK,PK,F1,N0007680009,Nonresident Alien,I,AS,PHD-GEOL,AS,PHD,GEOL,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,6,3.611111,67.0,Stillwater,"Abdel Salam, Mohamed G.",mohamed.abdel_salam@okstate.edu,NaN,NaT,201720,201840.0,NaN,mabbasi,salman.abbasi@okstate.edu,abbasi7@hotmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201160,201720.0,2016-08-31,2016-10-24,Admitted,AS,PHD,GEOL,N,New First Time,FC1331; FC1917,"Quaid-E-Azam Univ, Islamabad; Univ Of The Punjab"
6,201860,A10487104,Song,Ja-Hyun,NaN,NaN,Jahyun,Enrolled,F,1978-10-14,M,IN,KS,KS,F1,N0008644956,Nonresident Alien,I,AS,PHD-HS,HS,PHD,HS,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,2,3.812500,111.0,Stillwater,"Qu, Hailin",h.qu@okstate.edu,NaN,NaT,201460,201820.0,NaN,jahyun,jahyun@okstate.edu,s.jahyun@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201220,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,6543; FC0310,Oklahoma City University; Chung-Ang Univ
7,201860,A10496067,Tran,Duy,Duc,NaN,Duy,Enrolled,M,1986-10-10,S,IN,VM,VM,F1,N0003563732,Nonresident Alien,I,AS,PHD-ELEN,EN,PHD,ELEN,NaN,GR,GD,GD,C,Continuing,C,Continuing,FT,2,3.842105,111.0,Stillwater,"Sheng, Weihua",weihua.sheng@okstate.edu,NaN,NaT,201260,201840.0,NaN,duydt,duydt@okstate.edu,utddelta@gmail.com,716 N. Husband,Apt #16,Stillwater,OK,74075,NaN,195/16 Xo Viet Nghe Tinh,"Ward 17th, Binh Thanh District",Hochiminh,NaN,NaN,Vietnam,201120,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,FC2150,Vietnam Natl Univ Ho Chi Minh
8,201860,A10629166,Mutala,David,M,NaN,David,Enrolled,M,1984-04-26,S,IN,ZA,ZA,F1,N0024074736,Nonresident Alien,I,AS,MS-INTL,GR,MS,INTL,NaN,GR,GM,GM,C,Continuing,C,Continuing,FT,6,4.000000,15.0,Stillwater,"Voss, Kevin E.",kevin.voss@okstate.edu,"Jenswold, Joel M.",NaT,201760,201840.0,NaN,mutala,david.mutala@okstate.edu,davidmutala@hotmail.com,613 Sw 26th,NaN,Lawton,OK,73505,NaN,Dhahran Tower,Prince Sultan Rd,Al Khobar,NaN,31952,Saudi Arabia,201760,201760.0,2017-01-30,2017-03-06,Admitted,GR,MS,INTL,N,New First Time,6080,Cameron University
9,201860,A11090327,Singh,Rashmi,NaN,NaN,Rashmi,Enrolled,F,1976-08-16,M,IN,IN,IN,F3,NaN,Nonresident Alien,R,AS,MS-COUN,ED,MS,COUN,NaN,GR,GM,GM,C,Continuing,C,Continuing,3Q,7,4.000000,119.0,Stillwater/Tulsa,"Crethar, Hugh C.",crethar@okstate.edu,NaN,NaT,201760,201840.0,NaN,rashmis,rashmi.singh@okstate.edu,tannusingh@gmail.com,5919 E 53rd St,NaN,Tulsa,OK,74135,NaN,5919 E 53rd St,NaN,Tulsa,OK,74135-7715,NaN,200560,201760.0,2017-04-14,2017-04-14,Admitted,ED,MS,COUN,N,New First Time,DC0224; FC0998; FC1260; FC2126,Osu Ctr For Healh Sciences; Maharaja Sayajirao...

In [7]:
df1 =df.copy()

In [8]:
df1.columns = df1.columns.str.replace(' ','_')

In [9]:
df1.head(5)

,Curr_Term,Banner_ID,Last_Name,First_Name,Middle_Name,Name_Suffix,Preferred_First_Name,Enrolled/Admitted_Status,Gender,Birth_Date,...,Application_Date,Admit_Decision_Date,Admit_Decision,Admit_College,Admit_Degree,Admit_Major,Admit_Student_Population,Admit_Student_Population_Desc,All_Prior_Colleges,All_Prior_College_Names
0,201860,A10005577,Seol,Jong-Ho,NaN,NaN,Jongho,Enrolled,M,1972-04-06,...,2017-04-11,2017-04-13,Admitted,AS,PHD,CS,N,New First Time,FC1384,Samchok Natl Univ
1,201860,A10010945,Yerramsetti,Praveen,Nagh,NaN,Praveen,Enrolled,M,1976-12-20,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,FC0087; FC1235; FC0540; FC2126,Andhra University; Osmania Univ; Gitam Univers...
2,201860,A10042328,Loh,Weng,Kheong,NaN,Ben,Enrolled,M,1982-04-27,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201860,A10042670,Etlapur,Smitha,NaN,NaN,Smitha,Enrolled,F,1983-03-18,...,2016-06-21,2016-08-01,Admitted,GR,GCRT,BDM,N,New First Time,6546; FC1235,Oklahoma State Univ Stillwater; Osmania Univ
4,201860,A10042761,Jayaseelan,Hema,NaN,NaN,Hema,Enrolled,F,1979-03-18,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,FC0200,Bharathiar Univ

In [10]:
df1.describe(include=['object']) #get summary of categorical variables

,Banner_ID,Last_Name,First_Name,Middle_Name,Name_Suffix,Preferred_First_Name,Enrolled/Admitted_Status,Gender,Marital_Status,Citizenship_Type,...,Perm_Zip,Perm_Country,Admit_Decision,Admit_College,Admit_Degree,Admit_Major,Admit_Student_Population,Admit_Student_Population_Desc,All_Prior_Colleges,All_Prior_College_Names
count,1765,1765,1765,649,62,1562,1765,1765,1107,1765,...,1503,1123,1393,1393,1393,1393,1393,1393,1446,1446
unique,1765,1209,1415,527,5,1261,1,2,4,2,...,1061,69,3,9,30,105,7,7,792,789
top,A20140837,Li,Mohammed,A,Sr.,Ali,Enrolled,M,S,IN,...,74075,China (Mainland),Admitted,EN,MS,AGBU,N,New First Time,FC0280,China Agricultural University
freq,1,35,28,15,47,23,1765,1138,861,1759,...,118,311,1247,460,363,91,918,918,94,94

In [13]:
#Apply Function
#Create a new function:
def num_missing(x):
  return sum(x.isnull())
#Applying per column:
print("Missing values per column:")
print(df1.apply(num_missing, axis=0)) #axis=0 defines that function is to be applied on each column

Missing values per column:
Curr_Term                            0
Banner_ID                            0
Last_Name                            0
First_Name                           0
Middle_Name                       1116
Name_Suffix                       1703
Preferred_First_Name               203
Enrolled/Admitted_Status             0
Gender                               0
Birth_Date                           0
Marital_Status                     658
Citizenship_Type                     0
Nation_of_Citizenship                1
Nation_of_Birth                     63
Visa_Type                            1
SEVIS_Number                       304
Reported_Race                        0
Residency                            0
Student_Status                       0
Curr_Program                         0
Curr_College                         0
Curr_Degree                          0
Curr_Major_1                         0
Curr_Major_2                      1763
Curr_Level                           0
Curr_Class                           0
Class_Attr                         789
Curr_SGASTDN_Student_Type            0
Curr_SGASTDN_Student_Type_Desc       0
Derived_Student_Type                 0
Derived_Student_Type_Desc            0
Time_Status                          0
Curr_AHrs                            0
Overall_GPA                        420
Overall_EHrs                       420
Campus(es)                           0
Primary_Advisor                     95
Primary_Advisor_Email_Address       99
Secondary_Advisor(s)              1376
Enrollment_Date                   1764
Catalog_Term                         0
Last_Enrolled_Term                 508
Grad_App_Term                     1688
OKey_Username                        0
Student_Inst_Email_Address           1
Student_Alt_Email_Address            3
Local_Street_1                    1287
Local_Street_2                    1577
Local_City                        1287
Local_State                       1348
Local_Zip                         1295
Local_Country                     1703
Perm_Street_1                      192
Perm_Street_2                     1176
Perm_City                          192
Perm_State                        1122
Perm_Zip                           262
Perm_Country                       642
First_Admit_Term                     0
Admit_Term                         372
Application_Date                   372
Admit_Decision_Date                372
Admit_Decision                     372
Admit_College                      372
Admit_Degree                       372
Admit_Major                        372
Admit_Student_Population           372
Admit_Student_Population_Desc      372
All_Prior_Colleges                 319
All_Prior_College_Names            319
dtype: int64